### ISSUE TITLE
Epic 2: Replace tm-db database interface with new cosmos-db

### ISSUE THREAD

**Issue by i-norden** [vulcanize/cosmos-sdk#2]
Currently the SDK uses tm-db as its low-level database interface. Here we create a new interface to replace tm-db and support ADR-040. This interface will be packaged as part of the SDK. This interface will only support databases which support efficient DB Snapshot. At the time of writing we are going to support RocksDB and BadgerDB.

Our new interface will
* use batched transactions
* support versioning 
* support direct querying and abci.Querying
* needs to support the `MapStore` interface underpinning the SMT
* be generic enough to work on top of our two selected databases: RocksDB and BadgerDB

After creating the interface we need to integrate it into the SDK, replacing the dependency on tm-db.

**Comment by i-norden** [comment]
## MapStore updates

We will need to update the `MapStore` interface used by the LazyLedger SMT to expose needed features from the backend DB.

### Batch support

If we want to implement efficient batched writes to the SMT, that could be supported in the following way. The tree will need to be able to read as well as write to the batch itself while building it, using something closer to a transaction object.
  * RocksDB has a [Write Batch With Index](https://github.com/facebook/rocksdb/wiki/Write-Batch-With-Index) utility which allows this.
  * BadgerDB's `WriteBatch` does not support `Get`s, but, as it is a relatively simple wrapper around a transaction, we could just use `Txn`.

These writable batch types would be wrapped in the `MapStore` interface. The SMT would need a new interface type to represent the batch (e.g. `WriteBatch`). This would wrap a derived `SparseMerkleTree` object using the transaction object as its `MapStore`. All normal SMT operations would then be available on the batch.

### Versioning and snapshots

Creating state sync snapshots is [not required](https://github.com/cosmos/cosmos-sdk/pull/8430#discussion_r626879836) for SMT data.

Versioning may not be needed either; however, if it is desired, it could be implemented with a `MapStore.GetAt([]byte, uint64)` method, which forwards to a `DB.GetAt()` method as described [above](#versioning).

**Comment by roysc** [comment]
Feature PR on Cosmos SDK: https://github.com/cosmos/cosmos-sdk/pull/9573

**Comment by i-norden** [comment]
Closing, see https://github.com/cosmos/cosmos-sdk/issues/9816 and child issues,  tracking on [zenhub](https://app.zenhub.com/workspaces/cosmos-sdk-6080515f8a37bc001bd5488a/board?filterLogic=any&repos=51193526&showPRs=false)
