### ISSUE TITLE
Task: DB Migration script/tools

### ISSUE THREAD

**Issue by i-norden** [vulcanize/cosmos-sdk#7]
We need to write a set of tools for migrating old IAVL state to the new SMT + state storage format. This will be accomplished by performing a JSON dump of the IAVL data, and then loading that dump into the SMT + state storage format as the genesis state for a new Tendermint blockchain.

**Comment by tac0turtle** [comment]
Hey, this should not require any new tools. We do data dumps to json and back into the tree for upgrades. Modules should handle this internally.

**Comment by i-norden** [comment]
Closing, see https://github.com/cosmos/cosmos-sdk/issues/9816 and child issues,  tracking on [zenhub](https://app.zenhub.com/workspaces/cosmos-sdk-6080515f8a37bc001bd5488a/board?filterLogic=any&repos=51193526&showPRs=false)
