### ISSUE TITLE
Write a design md for DB snapshotting for state sync 

### ISSUE THREAD

**Issue by i-norden** [vulcanize/cosmos-sdk#9]
Detailed design documentation that we can upstream ahead of time to reach consensus on the approach before diving into the implementation. 

Snapshotting for state sync
* DB snapshotting approach using the updates tm-dbv2 interface that leverages the DB snapshotting methods of BadgerDB and RocksDB
* Precisely how this new interface is used by the Snapshotter and multistore.Snashot 

SC and SS decoupling
* Multistore retains a mapping of StoreKey to a Store tuple: (SCKVStore, SSKVStore)
* SCKVStore remains IAVL for now
* SSKVStore introduces the new state store buckets

**Comment by roysc** [comment]
HackMD draft at https://hackmd.io/dIt8ZaILTZSFpyqas6kTEw
